nod_Corporate_homepage:
    path:     /corporate
    defaults: { _controller: NodCorporateBundle:Corporate:index }
    
nod_Corporate_new:
    path:     /newcoporate
    defaults: { _controller: NodCorporateBundle:Corporate:new }
    
nod_Work_homepage:
    path:     /work
    defaults: { _controller: NodCorporateBundle:Corporate:index }
    
nod_Work_new:
    path:     /newwork
    defaults: { _controller: NodCorporateBundle:Corporate:new }

nod_Work_research:
    path:     /researchwork
    defaults: { _controller: NodCorporateBundle:Corporate:research }