equipement:
    resource: "@NodEquipementBundle/Resources/config/routing.yml"
    prefix:   /

metier:
    resource: "@NodMetierBundle/Resources/config/routing.yml"
    prefix:   /

personage:
    resource: "@NodPersonageBundle/Resources/config/routing.yml"
    prefix:   /

nod_core:
    resource: "@NodCoreBundle/Resources/config/routing.yml"
    prefix:   /
