nod_corporate:
    resource: "@NodCorporateBundle/Resources/config/routing.yml"
    prefix:   /

nod_user:
    resource: "@NodUserBundle/Resources/config/routing.yml"
    prefix:   /

nod_character:
    resource: "@NodCharacterBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /