index:
    path:   /
    defaults: { _controller: AppBundle:Default:index }

test: 
    path:   /test
    defaults: { _controller: AppBundle:Default:test }
    
demo: 
    path:   /demo
    defaults: { _controller: AppBundle:Default:demo }